sudo: false
language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=flake8
    - python: 3.6
      env: TOX_ENV=py3flake8
    - python: 2.7
      env: TOX_ENV=py27
    - python: 3.4
      env: TOX_ENV=py34
    - python: 3.5
      env: TOX_ENV=py35
    - python: 3.6
      env: TOX_ENV=py36
    - python: pypy
      env: TOX_ENV=pypy

before_install:
  - pip install codecov
install:
  - pip install tox
script:
  - make testone TOX_ENV="$TOX_ENV"
after_success:
  - codecov
