sudo: false
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py3flake8
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy

before_install:
  - pip install codecov
install:
  - pip install tox
script:
  - make testone TOX_ENV="$TOX_ENV"
after_success:
  - codecov
